import type { UnifiedTheme } from '../theme'

export function exportNvim(theme: UnifiedTheme): string {
  const hl = (group: string, fg?: string, bg?: string, extra = '') => {
    const parts = [
      fg ? `fg = "${fg}"` : '',
      bg ? `bg = "${bg}"` : '',
      extra,
    ].filter(Boolean).join(', ')
    return `  vim.api.nvim_set_hl(0, "${group}", { ${parts} })`
  }
  const slug = theme.name.toLowerCase().replace(/\s+/g, '_')

  return `-- ${theme.name}
-- Generated by ThemeCrafter
local M = {}

function M.setup()
  vim.o.termguicolors = true
  vim.g.colors_name = "${slug}"

  -- Editor UI
${hl('Normal',       theme.editor.foreground, theme.editor.background)}
${hl('NormalFloat',  theme.editor.foreground, theme.editor.background)}
${hl('Cursor',       theme.editor.background, theme.editor.cursor)}
${hl('CursorLine',   undefined,               theme.editor.lineHighlight)}
${hl('CursorLineNr', theme.editor.lineNumberActive)}
${hl('LineNr',       theme.editor.lineNumber)}
${hl('Visual',       undefined,               theme.editor.selection)}
${hl('VertSplit',    theme.editor.border)}
${hl('SignColumn',   undefined,               theme.editor.background)}
${hl('StatusLine',   theme.editor.foreground, theme.editor.lineHighlight)}
${hl('Pmenu',        theme.editor.foreground, theme.editor.lineHighlight)}
${hl('PmenuSel',     theme.editor.background, theme.syntax.function)}

  -- Base syntax
${hl('Comment',   theme.syntax.comment,     undefined, 'italic = true')}
${hl('Keyword',   theme.syntax.keyword)}
${hl('String',    theme.syntax.string)}
${hl('Number',    theme.syntax.number)}
${hl('Float',     theme.syntax.number)}
${hl('Function',  theme.syntax.function)}
${hl('Identifier',theme.syntax.variable)}
${hl('Type',      theme.syntax.type)}
${hl('Operator',  theme.syntax.operator)}
${hl('Delimiter', theme.syntax.punctuation)}
${hl('Tag',       theme.syntax.tag)}
${hl('Constant',  theme.syntax.constant)}
${hl('Special',   theme.syntax.builtin)}
${hl('PreProc',   theme.syntax.keyword)}

  -- Tree-sitter
${hl('@comment',            theme.syntax.comment,    undefined, 'italic = true')}
${hl('@keyword',            theme.syntax.keyword)}
${hl('@string',             theme.syntax.string)}
${hl('@number',             theme.syntax.number)}
${hl('@function',           theme.syntax.function)}
${hl('@function.builtin',   theme.syntax.builtin)}
${hl('@variable',           theme.syntax.variable)}
${hl('@variable.parameter', theme.syntax.parameter)}
${hl('@type',               theme.syntax.type)}
${hl('@operator',           theme.syntax.operator)}
${hl('@punctuation',        theme.syntax.punctuation)}
${hl('@tag',                theme.syntax.tag)}
${hl('@tag.attribute',      theme.syntax.attribute)}
${hl('@constant',           theme.syntax.constant)}

  -- Terminal colors
  vim.g.terminal_color_0  = "${theme.terminal.black}"
  vim.g.terminal_color_1  = "${theme.terminal.red}"
  vim.g.terminal_color_2  = "${theme.terminal.green}"
  vim.g.terminal_color_3  = "${theme.terminal.yellow}"
  vim.g.terminal_color_4  = "${theme.terminal.blue}"
  vim.g.terminal_color_5  = "${theme.terminal.magenta}"
  vim.g.terminal_color_6  = "${theme.terminal.cyan}"
  vim.g.terminal_color_7  = "${theme.terminal.white}"
  vim.g.terminal_color_8  = "${theme.terminal.brightBlack}"
  vim.g.terminal_color_9  = "${theme.terminal.brightRed}"
  vim.g.terminal_color_10 = "${theme.terminal.brightGreen}"
  vim.g.terminal_color_11 = "${theme.terminal.brightYellow}"
  vim.g.terminal_color_12 = "${theme.terminal.brightBlue}"
  vim.g.terminal_color_13 = "${theme.terminal.brightMagenta}"
  vim.g.terminal_color_14 = "${theme.terminal.brightCyan}"
  vim.g.terminal_color_15 = "${theme.terminal.brightWhite}"
end

return M
`
}
