import type { UnifiedTheme } from '../theme'

const slug = (t: UnifiedTheme) => t.name.toLowerCase().replace(/\s+/g, '_')

export function exportAlacritty(theme: UnifiedTheme): string {
  const { editor: e, terminal: t } = theme
  return `# ${theme.name} — Alacritty (Generated by ThemeCrafter)
# ~/.config/alacritty/themes/${slug(theme)}.toml
# Import: import = ["~/.config/alacritty/themes/${slug(theme)}.toml"]

[colors.primary]
background = "${e.background}"
foreground = "${e.foreground}"

[colors.cursor]
cursor = "${e.cursor}"
text   = "${e.background}"

[colors.selection]
background = "${e.selection}"
text       = "CellForeground"

[colors.normal]
black   = "${t.black}"
red     = "${t.red}"
green   = "${t.green}"
yellow  = "${t.yellow}"
blue    = "${t.blue}"
magenta = "${t.magenta}"
cyan    = "${t.cyan}"
white   = "${t.white}"

[colors.bright]
black   = "${t.brightBlack}"
red     = "${t.brightRed}"
green   = "${t.brightGreen}"
yellow  = "${t.brightYellow}"
blue    = "${t.brightBlue}"
magenta = "${t.brightMagenta}"
cyan    = "${t.brightCyan}"
white   = "${t.brightWhite}"
`
}

export function exportKitty(theme: UnifiedTheme): string {
  const { editor: e, terminal: t } = theme
  return `# ${theme.name} — Kitty (Generated by ThemeCrafter)
# ~/.config/kitty/themes/${slug(theme)}.conf
# Include: include themes/${slug(theme)}.conf

background           ${e.background}
foreground           ${e.foreground}
cursor               ${e.cursor}
cursor_text_color    ${e.background}
selection_background ${e.selection}
selection_foreground none

color0  ${t.black}
color8  ${t.brightBlack}
color1  ${t.red}
color9  ${t.brightRed}
color2  ${t.green}
color10 ${t.brightGreen}
color3  ${t.yellow}
color11 ${t.brightYellow}
color4  ${t.blue}
color12 ${t.brightBlue}
color5  ${t.magenta}
color13 ${t.brightMagenta}
color6  ${t.cyan}
color14 ${t.brightCyan}
color7  ${t.white}
color15 ${t.brightWhite}
`
}

export function exportWezTerm(theme: UnifiedTheme): string {
  const { editor: e, terminal: t } = theme
  return `-- ${theme.name} — WezTerm (Generated by ThemeCrafter)
-- ~/.config/wezterm/colors/${slug(theme)}.toml

[colors]
foreground    = "${e.foreground}"
background    = "${e.background}"
cursor_bg     = "${e.cursor}"
cursor_border = "${e.cursor}"
cursor_fg     = "${e.background}"
selection_bg  = "${e.selection}"
selection_fg  = "none"

ansi    = ["${t.black}","${t.red}","${t.green}","${t.yellow}","${t.blue}","${t.magenta}","${t.cyan}","${t.white}"]
brights = ["${t.brightBlack}","${t.brightRed}","${t.brightGreen}","${t.brightYellow}","${t.brightBlue}","${t.brightMagenta}","${t.brightCyan}","${t.brightWhite}"]
`
}
export function exportGhostty(theme: UnifiedTheme): string {
  const { editor: e, terminal: t } = theme
  return `# ${theme.name} — Ghostty (Generated by ThemeCrafter)
# Place at: ~/.config/ghostty/themes/${slug(theme)}
# Activate:  theme = ${slug(theme)}

background                    = ${e.background.replace('#', '')}
foreground                    = ${e.foreground.replace('#', '')}
cursor-color                  = ${e.cursor.replace('#', '')}
selection-background          = ${e.selection.replace('#', '')}
selection-foreground          = ${e.foreground.replace('#', '')}

palette = 0=${t.black}
palette = 1=${t.red}
palette = 2=${t.green}
palette = 3=${t.yellow}
palette = 4=${t.blue}
palette = 5=${t.magenta}
palette = 6=${t.cyan}
palette = 7=${t.white}
palette = 8=${t.brightBlack}
palette = 9=${t.brightRed}
palette = 10=${t.brightGreen}
palette = 11=${t.brightYellow}
palette = 12=${t.brightBlue}
palette = 13=${t.brightMagenta}
palette = 14=${t.brightCyan}
palette = 15=${t.brightWhite}
`
}
