import type { UnifiedTheme } from '../theme'

export function exportTmux(theme: UnifiedTheme): string {
  const { editor: e, syntax: s, terminal: t } = theme
  return `# ${theme.name} — tmux theme (Generated by ThemeCrafter)
# Paste into ~/.tmux.conf

set -g status-style              "bg=${e.lineHighlight},fg=${e.foreground}"
set -g status-left-style         "bg=${s.keyword},fg=${e.background},bold"
set -g status-right-style        "bg=${e.lineHighlight},fg=${e.lineNumber}"
set -g window-status-style       "bg=${e.lineHighlight},fg=${e.lineNumber}"
set -g window-status-current-style "bg=${s.function},fg=${e.background},bold"
set -g window-status-bell-style  "bg=${s.type},fg=${e.background}"
set -g pane-border-style         "fg=${e.border}"
set -g pane-active-border-style  "fg=${s.function}"
set -g message-style             "bg=${e.selection},fg=${e.foreground}"
set -g message-command-style     "bg=${e.selection},fg=${s.keyword}"
set -g mode-style                "bg=${e.selection},fg=${e.foreground}"
set -g copy-mode-match-style     "bg=${s.string},fg=${e.background}"
set -g copy-mode-current-match-style "bg=${s.function},fg=${e.background}"

set -g status-left " #S "
set -g status-right " %H:%M  %d %b "
set -g status-left-length 20
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
`
}
