import type { UnifiedTheme } from '../theme'

export function exportVSCode(theme: UnifiedTheme): string {
  return JSON.stringify({
    name: theme.name,
    type: theme.type,
    colors: {
      'editor.background': theme.editor.background,
      'editor.foreground': theme.editor.foreground,
      'editorCursor.foreground': theme.editor.cursor,
      'editor.selectionBackground': theme.editor.selection,
      'editor.lineHighlightBackground': theme.editor.lineHighlight,
      'editorLineNumber.foreground': theme.editor.lineNumber,
      'editorLineNumber.activeForeground': theme.editor.lineNumberActive,
      'editorGroup.border': theme.editor.border,
      'editorGutter.background': theme.editor.gutter,
      'terminal.ansiBlack': theme.terminal.black,
      'terminal.ansiRed': theme.terminal.red,
      'terminal.ansiGreen': theme.terminal.green,
      'terminal.ansiYellow': theme.terminal.yellow,
      'terminal.ansiBlue': theme.terminal.blue,
      'terminal.ansiMagenta': theme.terminal.magenta,
      'terminal.ansiCyan': theme.terminal.cyan,
      'terminal.ansiWhite': theme.terminal.white,
      'terminal.ansiBrightBlack': theme.terminal.brightBlack,
      'terminal.ansiBrightRed': theme.terminal.brightRed,
      'terminal.ansiBrightGreen': theme.terminal.brightGreen,
      'terminal.ansiBrightYellow': theme.terminal.brightYellow,
      'terminal.ansiBrightBlue': theme.terminal.brightBlue,
      'terminal.ansiBrightMagenta': theme.terminal.brightMagenta,
      'terminal.ansiBrightCyan': theme.terminal.brightCyan,
      'terminal.ansiBrightWhite': theme.terminal.brightWhite,
    },
    tokenColors: [
      { scope: ['comment'],                                    settings: { foreground: theme.syntax.comment, fontStyle: 'italic' } },
      { scope: ['keyword', 'keyword.control', 'storage.type'],settings: { foreground: theme.syntax.keyword } },
      { scope: ['string', 'string.quoted'],                    settings: { foreground: theme.syntax.string } },
      { scope: ['constant.numeric'],                           settings: { foreground: theme.syntax.number } },
      { scope: ['entity.name.function', 'support.function'],  settings: { foreground: theme.syntax.function } },
      { scope: ['variable', 'variable.other'],                 settings: { foreground: theme.syntax.variable } },
      { scope: ['entity.name.type', 'support.type'],           settings: { foreground: theme.syntax.type } },
      { scope: ['keyword.operator'],                           settings: { foreground: theme.syntax.operator } },
      { scope: ['punctuation'],                                settings: { foreground: theme.syntax.punctuation } },
      { scope: ['entity.name.tag'],                            settings: { foreground: theme.syntax.tag } },
      { scope: ['entity.other.attribute-name'],                settings: { foreground: theme.syntax.attribute } },
      { scope: ['constant.language', 'support.constant'],      settings: { foreground: theme.syntax.constant } },
      { scope: ['support.class', 'support.type.builtin'],      settings: { foreground: theme.syntax.builtin } },
      { scope: ['variable.parameter'],                         settings: { foreground: theme.syntax.parameter } },
    ],
  }, null, 2)
}
